dtcc_source_schema = {
    "Dissemination_Identifier": "String",
    "Original_Dissemination_Identifier": "Nullable(String)",
    "Action_type": "Nullable(String)",
    "Event_type": "Nullable(String)",
    "Event_timestamp": "String",
    "Amendment_indicator": "Nullable(String)",
    "Asset_Class": "Nullable(String)",
    "Product_name": "Nullable(String)",
    "Cleared": "Nullable(String)",
    "Mandatory_clearing_indicator": "Nullable(String)",
    "Execution_Timestamp": "Nullable(String)",
    "Effective_Date": "Nullable(String)",
    "Expiration_Date": "Nullable(String)",
    "Maturity_date_of_the_underlier": "Nullable(String)",
    "Non_standardized_term_indicator": "Nullable(String)",
    "Platform_identifier": "Nullable(String)",
    "Prime_brokerage_transaction_indicator": "Nullable(String)",
    "Block_trade_election_indicator": "Nullable(String)",
    "Large_notional_off_facility_swap_election_indicator": "Nullable(String)",
    "Notional_amount_Leg_1": "Nullable(String)",
    "Notional_amount_Leg_2": "Nullable(String)",
    "Notional_currency_Leg_1": "Nullable(String)",
    "Notional_currency_Leg_2": "Nullable(String)",
    "Notional_quantity_Leg_1": "Nullable(String)",
    "Notional_quantity_Leg_2": "Nullable(String)",
    "Total_notional_quantity_Leg_1": "Nullable(String)",
    "Total_notional_quantity_Leg_2": "Nullable(String)",
    "Quantity_frequency_multiplier_Leg_1": "Nullable(String)",
    "Quantity_frequency_multiplier_Leg_2": "Nullable(String)",
    "Quantity_unit_of_measure_Leg_1": "Nullable(String)",
    "Quantity_unit_of_measure_Leg_2": "Nullable(String)",
    "Quantity_frequency_Leg_1": "Nullable(String)",
    "Quantity_frequency_Leg_2": "Nullable(String)",
    "Notional_amount_in_effect_on_associated_effective_date_Leg_1": "Nullable(String)",
    "Notional_amount_in_effect_on_associated_effective_date_Leg_2": "Nullable(String)",
    "Effective_date_of_the_notional_amount_Leg_1": "Nullable(String)",
    "Effective_date_of_the_notional_amount_Leg_2": "Nullable(String)",
    "End_date_of_the_notional_amount_Leg_1": "Nullable(String)",
    "End_date_of_the_notional_amount_Leg_2": "Nullable(String)",
    "Call_amount_Leg_1": "Nullable(String)",
    "Call_amount_Leg_2": "Nullable(String)",
    "Call_currency_Leg_1": "Nullable(String)",
    "Call_currency_Leg_2": "Nullable(String)",
    "Put_amount_Leg_1": "Nullable(String)",
    "Put_amount_Leg_2": "Nullable(String)",
    "Put_currency_Leg_1": "Nullable(String)",
    "Put_currency_Leg_2": "Nullable(String)",
    "Exchange_rate": "Nullable(String)",
    "Exchange_rate_basis": "Nullable(String)",
    "First_exercise_date": "Nullable(String)",
    "Fixed_rate_Leg_1": "Nullable(String)",
    "Fixed_rate_Leg_2": "Nullable(String)",
    "Option_Premium_Amount": "Nullable(String)",
    "Option_Premium_Currency": "Nullable(String)",
    "Price": "Nullable(String)",
    "Price_unit_of_measure": "Nullable(String)",
    "Spread_Leg_1": "Nullable(String)",
    "Spread_Leg_2": "Nullable(String)",
    "Spread_currency_Leg_1": "Nullable(String)",
    "Spread_currency_Leg_2": "Nullable(String)",
    "Strike_Price": "Nullable(String)",
    "Strike_price_currency_currency_pair": "Nullable(String)",
    "Post_priced_swap_indicator": "Nullable(String)",
    "Price_currency": "Nullable(String)",
    "Price_notation": "Nullable(String)",
    "Spread_notation_Leg_1": "Nullable(String)",
    "Spread_notation_Leg_2": "Nullable(String)",
    "Strike_price_notation": "Nullable(String)",
    "Fixed_rate_day_count_convention_leg_1": "Nullable(String)",
    "Fixed_rate_day_count_convention_leg_2": "Nullable(String)",
    "Floating_rate_day_count_convention_leg_1": "Nullable(String)",
    "Floating_rate_day_count_convention_leg_2": "Nullable(String)",
    "Floating_rate_reset_frequency_period_leg_1": "Nullable(String)",
    "Floating_rate_reset_frequency_period_leg_2": "Nullable(String)",
    "Floating_rate_reset_frequency_period_multiplier_leg_1": "Nullable(String)",
    "Floating_rate_reset_frequency_period_multiplier_leg_2": "Nullable(String)",
    "Other_payment_amount": "Nullable(String)",
    "Fixed_rate_payment_frequency_period_Leg_1": "Nullable(String)",
    "Floating_rate_payment_frequency_period_Leg_1": "Nullable(String)",
    "Fixed_rate_payment_frequency_period_Leg_2": "Nullable(String)",
    "Floating_rate_payment_frequency_period_Leg_2": "Nullable(String)",
    "Fixed_rate_payment_frequency_period_multiplier_Leg_1": "Nullable(String)",
    "Floating_rate_payment_frequency_period_multiplier_Leg_1": "Nullable(String)",
    "Fixed_rate_payment_frequency_period_multiplier_Leg_2": "Nullable(String)",
    "Floating_rate_payment_frequency_period_multiplier_Leg_2": "Nullable(String)",
    "Other_payment_type": "Nullable(String)",
    "Other_payment_currency": "Nullable(String)",
    "Settlement_currency_Leg_1": "Nullable(String)",
    "Settlement_currency_Leg_2": "Nullable(String)",
    "Settlement_location_Leg_1": "Nullable(String)",
    "Settlement_location_Leg_2": "Nullable(String)",
    "Collateralisation_category": "Nullable(String)",
    "Custom_basket_indicator": "Nullable(String)",
    "Index_factor": "Nullable(String)",
    "Underlier_ID_Leg_1": "Nullable(String)",
    "Underlier_ID_Leg_2": "Nullable(String)",
    "Underlier_ID_source_Leg_1": "Nullable(String)",
    "Underlying_Asset_Name": "Nullable(String)",
    "Underlying_asset_subtype_or_underlying_contract_subtype_Leg_1": "Nullable(String)",
    "Underlying_asset_subtype_or_underlying_contract_subtype_Leg_2": "Nullable(String)",
    "Embedded_Option_type": "Nullable(String)",
    "Option_Type": "Nullable(String)",
    "Option_Style": "Nullable(String)",
    "Package_indicator": "Nullable(String)",
    "Package_transaction_price": "Nullable(String)",
    "Package_transaction_price_currency": "Nullable(String)",
    "Package_transaction_price_notation": "Nullable(String)",
    "Package_transaction_spread": "Nullable(String)",
    "Package_transaction_spread_currency": "Nullable(String)",
    "Package_transaction_spread_notation": "Nullable(String)",
    "Physical_delivery_location_Leg_1": "Nullable(String)",
    "Delivery_Type": "Nullable(String)",
    "_Report_Date": "Nullable(String)",
    "_Source_URL": "Nullable(String)",
    "_RecordID": "String"
    # "Report_Retrieval_Timestamp": 'Datetime64'
}

dtcc_source_schema2 = {
    "Dissemination_Identifier": "String",
    "Original_Dissemination_Identifier": "Nullable(String)",
    "Action_type": "Nullable(String)",
    "Event_type": "Nullable(String)",
    "Event_timestamp": "String",
    "Amendment_indicator": "Nullable(String)",
    "Asset_Class": "Nullable(String)",
    "Product_name": "Nullable(String)",
    "Cleared": "Nullable(String)",
    "Mandatory_clearing_indicator": "Nullable(String)",
    "Execution_Timestamp": "Nullable(String)",
    "Effective_Date": "Nullable(String)",
    "Expiration_Date": "Nullable(String)",
    "Maturity_date_of_the_underlier": "Nullable(String)",
    "Non_standardized_term_indicator": "Nullable(String)",
    "Platform_identifier": "Nullable(String)",
    "Prime_brokerage_transaction_indicator": "Nullable(String)",
    "Block_trade_election_indicator": "Nullable(String)",
    "Large_notional_off_facility_swap_election_indicator": "Nullable(String)",
    "Notional_amount_Leg_1": "Nullable(String)",
    "Notional_amount_Leg_2": "Nullable(String)",
    "Notional_currency_Leg_1": "Nullable(String)",
    "Notional_currency_Leg_2": "Nullable(String)",
    "Notional_quantity_Leg_1": "Nullable(String)",
    "Notional_quantity_Leg_2": "Nullable(String)",
    "Total_notional_quantity_Leg_1": "Nullable(String)",
    "Total_notional_quantity_Leg_2": "Nullable(String)",
    "Quantity_frequency_multiplier_Leg_1": "Nullable(String)",
    "Quantity_frequency_multiplier_Leg_2": "Nullable(String)",
    "Quantity_unit_of_measure_Leg_1": "Nullable(String)",
    "Quantity_unit_of_measure_Leg_2": "Nullable(String)",
    "Quantity_frequency_Leg_1": "Nullable(String)",
    "Quantity_frequency_Leg_2": "Nullable(String)",
    "Notional_amount_in_effect_on_associated_effective_date_Leg_1": "Nullable(String)",
    "Notional_amount_in_effect_on_associated_effective_date_Leg_2": "Nullable(String)",
    "Effective_date_of_the_notional_amount_Leg_1": "Nullable(String)",
    "Effective_date_of_the_notional_amount_Leg_2": "Nullable(String)",
    "End_date_of_the_notional_amount_Leg_1": "Nullable(String)",
    "End_date_of_the_notional_amount_Leg_2": "Nullable(String)",
    "Call_amount": "Nullable(String)",
    "Call_currency": "Nullable(String)",
    "Put_amount": "Nullable(String)",
    "Put_currency": "Nullable(String)",
    "Exchange_rate": "Nullable(String)",
    "Exchange_rate_basis": "Nullable(String)",
    "First_exercise_date": "Nullable(String)",
    "Fixed_rate_Leg_1": "Nullable(String)",
    "Fixed_rate_Leg_2": "Nullable(String)",
    "Option_Premium_Amount": "Nullable(String)",
    "Option_Premium_Currency": "Nullable(String)",
    "Price": "Nullable(String)",
    "Price_unit_of_measure": "Nullable(String)",
    "Spread_Leg_1": "Nullable(String)",
    "Spread_Leg_2": "Nullable(String)",
    "Spread_currency_Leg_1": "Nullable(String)",
    "Spread_currency_Leg_2": "Nullable(String)",
    "Strike_Price": "Nullable(String)",
    "Strike_price_currency_currency_pair": "Nullable(String)",
    "Post_priced_swap_indicator": "Nullable(String)",
    "Price_currency": "Nullable(String)",
    "Price_notation": "Nullable(String)",
    "Spread_notation_Leg_1": "Nullable(String)",
    "Spread_notation_Leg_2": "Nullable(String)",
    "Strike_price_notation": "Nullable(String)",
    "Fixed_rate_day_count_convention_leg_1": "Nullable(String)",
    "Fixed_rate_day_count_convention_leg_2": "Nullable(String)",
    "Floating_rate_day_count_convention_leg_1": "Nullable(String)",
    "Floating_rate_day_count_convention_leg_2": "Nullable(String)",
    "Floating_rate_reset_frequency_period_leg_1": "Nullable(String)",
    "Floating_rate_reset_frequency_period_leg_2": "Nullable(String)",
    "Floating_rate_reset_frequency_period_multiplier_leg_1": "Nullable(String)",
    "Floating_rate_reset_frequency_period_multiplier_leg_2": "Nullable(String)",
    "Other_payment_amount": "Nullable(String)",
    "Fixed_rate_payment_frequency_period_Leg_1": "Nullable(String)",
    "Floating_rate_payment_frequency_period_Leg_1": "Nullable(String)",
    "Fixed_rate_payment_frequency_period_Leg_2": "Nullable(String)",
    "Floating_rate_payment_frequency_period_Leg_2": "Nullable(String)",
    "Fixed_rate_payment_frequency_period_multiplier_Leg_1": "Nullable(String)",
    "Floating_rate_payment_frequency_period_multiplier_Leg_1": "Nullable(String)",
    "Fixed_rate_payment_frequency_period_multiplier_Leg_2": "Nullable(String)",
    "Floating_rate_payment_frequency_period_multiplier_Leg_2": "Nullable(String)",
    "Other_payment_type": "Nullable(String)",
    "Other_payment_currency": "Nullable(String)",
    "Settlement_currency_Leg_1": "Nullable(String)",
    "Settlement_currency_Leg_2": "Nullable(String)",
    "Settlement_location": "Nullable(String)",
    "Collateralisation_category": "Nullable(String)",
    "Custom_basket_indicator": "Nullable(String)",
    "Index_factor": "Nullable(String)",
    "Underlier_ID_Leg_1": "Nullable(String)",
    "Underlier_ID_Leg_2": "Nullable(String)",
    "Underlier_ID_source_Leg_1": "Nullable(String)",
    "Underlying_Asset_Name": "Nullable(String)",
    "Underlying_asset_subtype_or_underlying_contract_subtype_Leg_1": "Nullable(String)",
    "Underlying_asset_subtype_or_underlying_contract_subtype_Leg_2": "Nullable(String)",
    "Embedded_Option_type": "Nullable(String)",
    "Option_Type": "Nullable(String)",
    "Option_Style": "Nullable(String)",
    "Package_indicator": "Nullable(String)",
    "Package_transaction_price": "Nullable(String)",
    "Package_transaction_price_currency": "Nullable(String)",
    "Package_transaction_price_notation": "Nullable(String)",
    "Package_transaction_spread": "Nullable(String)",
    "Package_transaction_spread_currency": "Nullable(String)",
    "Package_transaction_spread_notation": "Nullable(String)",
    "Physical_delivery_location_Leg_1": "Nullable(String)",
    "Delivery_Type": "Nullable(String)",
    "Unique_Product_Identifier": "Nullable(String)",
    "UPI_FISN": "Nullable(String)",
    "UPI_Underlier_Name": "Nullable(String)",
    "_Report_Date": "Nullable(String)",
    "_Source_URL": "Nullable(String)",
    "_RecordID": "String"
    # "Report_Retrieval_Timestamp": 'Datetime64'
}


dtcc_staging_schema = {
    "Dissemination_Identifier": "String",
    "Original_Dissemination_Identifier": "Nullable(String)",
    "Action_type": "Nullable(String)",
    "Event_type": "Nullable(String)",
    "Event_timestamp": "DateTime64",
    "Amendment_indicator": "Nullable(String)",
    "Asset_Class": "Nullable(String)",
    "Product_name": "Nullable(String)",
    "Cleared": "Nullable(String)",
    "Mandatory_clearing_indicator": "Nullable(String)",
    "Execution_Timestamp": "Nullable(String)",
    "Effective_Date": "Nullable(String)",
    "Expiration_Date": "Nullable(String)",
    "Maturity_date_of_the_underlier": "Nullable(String)",
    "Non_standardized_term_indicator": "Nullable(String)",
    "Platform_identifier": "Nullable(String)",
    "Prime_brokerage_transaction_indicator": "Nullable(String)",
    "Block_trade_election_indicator": "Nullable(String)",
    "Large_notional_off_facility_swap_election_indicator": "Nullable(String)",
    "Notional_amount_Leg_1": "Nullable(Float64)",
    "Notional_amount_Leg_2": "Nullable(Float64)",
    "Notional_currency_Leg_1": "Nullable(String)",
    "Notional_currency_Leg_2": "Nullable(String)",
    "Notional_quantity_Leg_1": "Nullable(String)",
    "Notional_quantity_Leg_2": "Nullable(String)",
    "Total_notional_quantity_Leg_1": "Nullable(String)",
    "Total_notional_quantity_Leg_2": "Nullable(String)",
    "Quantity_frequency_multiplier_Leg_1": "Nullable(String)",
    "Quantity_frequency_multiplier_Leg_2": "Nullable(String)",
    "Quantity_unit_of_measure_Leg_1": "Nullable(String)",
    "Quantity_unit_of_measure_Leg_2": "Nullable(String)",
    "Quantity_frequency_Leg_1": "Nullable(String)",
    "Quantity_frequency_Leg_2": "Nullable(String)",
    "Notional_amount_in_effect_on_associated_effective_date_Leg_1": "Nullable(Float64)",
    "Notional_amount_in_effect_on_associated_effective_date_Leg_2": "Nullable(Float64)",
    "Effective_date_of_the_notional_amount_Leg_1": "Nullable(Date)",
    "Effective_date_of_the_notional_amount_Leg_2": "Nullable(Date)",
    "End_date_of_the_notional_amount_Leg_1": "Nullable(Date)",
    "End_date_of_the_notional_amount_Leg_2": "Nullable(Date)",
    "Call_amount_Leg_1": "Nullable(Float64)",
    "Call_amount_Leg_2": "Nullable(Float64)",
    "Call_currency_Leg_1": "Nullable(String)",
    "Call_currency_Leg_2": "Nullable(String)",
    "Put_amount_Leg_1": "Nullable(Float64)",
    "Put_amount_Leg_2": "Nullable(Float64)",
    "Put_currency_Leg_1": "Nullable(String)",
    "Put_currency_Leg_2": "Nullable(String)",
    "Exchange_rate": "Nullable(String)",
    "Exchange_rate_basis": "Nullable(String)",
    "First_exercise_date": "Nullable(String)",
    "Fixed_rate_Leg_1": "Nullable(String)",
    "Fixed_rate_Leg_2": "Nullable(String)",
    "Option_Premium_Amount": "Nullable(Float64)",
    "Option_Premium_Currency": "Nullable(String)",
    "Price": "Nullable(Float64)",
    "Price_unit_of_measure": "Nullable(String)",
    "Spread_Leg_1": "Nullable(Float64)",
    "Spread_Leg_2": "Nullable(Float64)",
    "Spread_currency_Leg_1": "Nullable(String)",
    "Spread_currency_Leg_2": "Nullable(String)",
    "Strike_Price": "Nullable(Float64)",
    "Strike_price_currency_currency_pair": "Nullable(String)",
    "Post_priced_swap_indicator": "Nullable(String)",
    "Price_currency": "Nullable(String)",
    "Price_notation": "Nullable(String)",
    "Spread_notation_Leg_1": "Nullable(String)",
    "Spread_notation_Leg_2": "Nullable(String)",
    "Strike_price_notation": "Nullable(String)",
    "Fixed_rate_day_count_convention_leg_1": "Nullable(String)",
    "Fixed_rate_day_count_convention_leg_2": "Nullable(String)",
    "Floating_rate_day_count_convention_leg_1": "Nullable(String)",
    "Floating_rate_day_count_convention_leg_2": "Nullable(String)",
    "Floating_rate_reset_frequency_period_leg_1": "Nullable(Int8)",
    "Floating_rate_reset_frequency_period_leg_2": "Nullable(Int8)",
    "Floating_rate_reset_frequency_period_multiplier_leg_1": "Nullable(Int8)",
    "Floating_rate_reset_frequency_period_multiplier_leg_2": "Nullable(Int8)",
    "Other_payment_amount": "Nullable(Float64)",
    "Fixed_rate_payment_frequency_period_Leg_1": "Nullable(Int8)",
    "Floating_rate_payment_frequency_period_Leg_1": "Nullable(Int8)",
    "Fixed_rate_payment_frequency_period_Leg_2": "Nullable(Int8)",
    "Floating_rate_payment_frequency_period_Leg_2": "Nullable(Int8)",
    "Fixed_rate_payment_frequency_period_multiplier_Leg_1": "Nullable(Float64)",
    "Floating_rate_payment_frequency_period_multiplier_Leg_1": "Nullable(Float64)",
    "Fixed_rate_payment_frequency_period_multiplier_Leg_2": "Nullable(Float64)",
    "Floating_rate_payment_frequency_period_multiplier_Leg_2": "Nullable(Float64)",
    "Other_payment_type": "Nullable(String)",
    "Other_payment_currency": "Nullable(String)",
    "Settlement_currency_Leg_1": "Nullable(String)",
    "Settlement_currency_Leg_2": "Nullable(String)",
    "Settlement_location_Leg_1": "Nullable(String)",
    "Settlement_location_Leg_2": "Nullable(String)",
    "Collateralisation_category": "Nullable(String)",
    "Custom_basket_indicator": "Nullable(String)",
    "Index_factor": "Nullable(String)",
    "Underlier_ID_Leg_1": "Nullable(String)",
    "Underlier_ID_Leg_2": "Nullable(String)",
    "Underlier_ID_source_Leg_1": "Nullable(String)",
    "Underlying_Asset_Name": "Nullable(String)",
    "Underlying_asset_subtype_or_underlying_contract_subtype_Leg_1": "Nullable(String)",
    "Underlying_asset_subtype_or_underlying_contract_subtype_Leg_2": "Nullable(String)",
    "Embedded_Option_type": "Nullable(String)",
    "Option_Type": "Nullable(String)",
    "Option_Style": "Nullable(String)",
    "Package_indicator": "Nullable(String)",
    "Package_transaction_price": "Nullable(String)",
    "Package_transaction_price_currency": "Nullable(String)",
    "Package_transaction_price_notation": "Nullable(String)",
    "Package_transaction_spread": "Nullable(String)",
    "Package_transaction_spread_currency": "Nullable(String)",
    "Package_transaction_spread_notation": "Nullable(String)",
    "Physical_delivery_location_Leg_1": "Nullable(String)",
    "Delivery_Type": "Nullable(String)",
    "_Report_Date": "Nullable(Date)",
    "_Source_URL": "Nullable(String)",
    "_RecordID": "String"
    # "Report_Retrieval_Timestamp": 'Datetime64'
}




ice_source_schema = {
    'Cleared': 'Nullable(String)',
    'Custom_basket_indicator': 'Nullable(String)',
    'Action_type': 'Nullable(String)',
    'Event_type': 'Nullable(String)',
    'Amendment_indicator': 'Nullable(String)',
    'Event_timestamp': 'String',
    'Notional_amount': 'Nullable(String)',
    'Notional_currency': 'Nullable(String)',
    'Notional_amount_schedule_-_notional_amount_in_effect_on_associated_effective_date': 'Nullable(String)',
    'Notional_amount_schedule_-_unadjusted_effective_date_of_the_notional_amount': 'Nullable(String)',
    'Notional_amount_schedule_-_unadjusted_end_date_of_the_notional_amount': 'Nullable(String)',
    'Call_amount': 'Nullable(String)',
    'Call_currency': 'Nullable(String)',
    'Put_amount': 'Nullable(String)',
    'Put_currency': 'Nullable(String)',
    'Package_indicator': 'Nullable(String)',
    'Package_transaction_price': 'Nullable(String)',
    'Package_transaction_price_currency': 'Nullable(String)',
    'Package_transaction_price_notation': 'Nullable(String)',
    'Package_transaction_spread': 'Nullable(String)',
    'Package_transaction_spread_currency': 'Nullable(String)',
    'Package_transaction_spread_notation': 'Nullable(String)',
    'Day_count_convention': 'Nullable(String)',
    'Floating_rate_reset_frequency_period': 'Nullable(String)',
    'Floating_rate_reset_frequency_period_multiplier': 'Nullable(String)',
    'Other_payment_type': 'Nullable(String)',
    'Other_payment_amount': 'Nullable(String)',
    'Other_payment_currency': 'Nullable(String)',
    'Payment_frequency_period': 'Nullable(String)',
    'Payment_frequency_period_multiplier': 'Nullable(String)',
    'Fixed_rate': 'Nullable(String)',
    'Post-priced_swap_indicator': 'Nullable(String)',
    'Spread': 'Nullable(String)',
    'Spread_currency': 'Nullable(String)',
    'Spread_notation': 'Nullable(String)',
    'Strike_price': 'Nullable(String)',
    'Strike_price_currency/currency_pair': 'Nullable(String)',
    'Strike_price_notation': 'Nullable(String)',
    'Option_premium_amount': 'Nullable(String)',
    'Option_premium_currency': 'Nullable(String)',
    'First_exercise_date': 'Nullable(String)',
    'Embedded_option_type': 'Nullable(String)',
    'Settlement_currency': 'Nullable(String)',
    'Settlement_location': 'Nullable(String)',
    'Non-standardized_term_indicator': 'Nullable(String)',
    'Block_trade_election_indicator': 'Nullable(String)',
    'Effective_date': 'Nullable(String)',
    'Expiration_date': 'Nullable(String)',
    'Execution_timestamp': 'Nullable(String)',
    'Platform_identifier': 'Nullable(String)',
    'Prime_brokerage_transaction_indicator': 'Nullable(String)',
    'Classification': 'Nullable(String)',
    'Reference_Entity_Name': 'Nullable(String)',
    'Reference_Entity_Ticker': 'Nullable(String)',
    'Seniority': 'Nullable(String)',
    'Restructuring': 'Nullable(String)',
    'Scheduled_Termination_Date': 'Nullable(String)',
    'Contract_Type': 'Nullable(String)',
    'Dissemination_identifier': 'String',
    'Original_dissemination_identifier': 'Nullable(String)',
    'Dissemination_timestamp': 'Nullable(String)',
    'Unique_product_identifier': 'Nullable(String)',
    '_Report_Date': 'Nullable(String)',
    '_Source_URL': 'Nullable(String)',
    '_RecordID': 'String'
    # "Report_Retrieval_Timestamp": 'Datetime64'
}


ice_staging_schema = {
    'Cleared': 'Nullable(String)',
    'Custom_basket_indicator': 'Nullable(String)',
    'Action_type': 'Nullable(String)',
    'Event_type': 'Nullable(String)',
    'Amendment_indicator': 'Nullable(String)',
    'Event_timestamp': 'Datetime64',
    'Notional_amount': 'Nullable(Float64)',
    'Notional_currency': 'Nullable(String)',
    'Notional_amount_schedule_-_notional_amount_in_effect_on_associated_effective_date': 'Nullable(Float64)',
    'Notional_amount_schedule_-_unadjusted_effective_date_of_the_notional_amount': 'Nullable(Date)',
    'Notional_amount_schedule_-_unadjusted_end_date_of_the_notional_amount': 'Nullable(Date)',
    'Call_amount': 'Nullable(Float64)',
    'Call_currency': 'Nullable(String)',
    'Put_amount': 'Nullable(Float64)',
    'Put_currency': 'Nullable(String)',
    'Package_indicator': 'Nullable(String)',
    'Package_transaction_price': 'Nullable(Float64)',
    'Package_transaction_price_currency': 'Nullable(String)',
    'Package_transaction_price_notation': 'Nullable(String)',
    'Package_transaction_spread': 'Nullable(Float64)',
    'Package_transaction_spread_currency': 'Nullable(String)',
    'Package_transaction_spread_notation': 'Nullable(String)',
    'Day_count_convention': 'Nullable(String)',
    'Floating_rate_reset_frequency_period': 'Nullable(String)',
    'Floating_rate_reset_frequency_period_multiplier': 'Nullable(Float64)',
    'Other_payment_type': 'Nullable(String)',
    'Other_payment_amount': 'Nullable(Float64)',
    'Other_payment_currency': 'Nullable(String)',
    'Payment_frequency_period': 'Nullable(String)',
    'Payment_frequency_period_multiplier': 'Nullable(Int)',
    'Fixed_rate': 'Nullable(String)',
    'Post-priced_swap_indicator': 'Nullable(String)',
    'Spread': 'Nullable(Float64)',
    'Spread_currency': 'Nullable(String)',
    'Spread_notation': 'Nullable(String)',
    'Strike_price': 'Nullable(Float64)',
    'Strike_price_currency/currency_pair': 'Nullable(String)',
    'Strike_price_notation': 'Nullable(String)',
    'Option_premium_amount': 'Nullable(Float64)',
    'Option_premium_currency': 'Nullable(String)',
    'First_exercise_date': 'Nullable(Date)',
    'Embedded_option_type': 'Nullable(String)',
    'Settlement_currency': 'Nullable(String)',
    'Settlement_location': 'Nullable(String)',
    'Non-standardized_term_indicator': 'Nullable(String)',
    'Block_trade_election_indicator': 'Nullable(String)',
    'Effective_date': 'Nullable(Date)',
    'Expiration_date': 'Nullable(Date)',
    'Execution_timestamp': 'Nullable(Datetime64)',
    'Platform_identifier': 'Nullable(String)',
    'Prime_brokerage_transaction_indicator': 'Nullable(String)',
    'Classification': 'Nullable(String)',
    'Reference_Entity_Name': 'Nullable(String)',
    'Reference_Entity_Ticker': 'Nullable(String)',
    'Seniority': 'Nullable(String)',
    'Restructuring': 'Nullable(String)',
    'Scheduled_Termination_Date': 'Nullable(Date)',
    'Contract_Type': 'Nullable(String)',
    'Dissemination_identifier': 'String',
    'Original_dissemination_identifier': 'Nullable(String)',
    'Dissemination_timestamp': 'Nullable(Datetime64)',
    'Unique_product_identifier': 'Nullable(String)',
    '_Report_Date': 'Nullable(String)',
    '_Source_URL': 'Nullable(String)',
    '_RecordID': 'String'
    # "Report_Retrieval_Timestamp": 'Datetime64'
}

# At some point these values change, again -- this map is to put field names in the same inclusive format
dtcc_map = {
    'Dissemination ID': 'Dissemination Identifier',
    'Original Dissemination ID': 'Original Dissemination Identifier',
    'Action Type': 'Action type',
    'Action': 'Action type',
    'Event Timestamp': 'Event timestamp',
    'Notional Amount 1': 'Notional amount-Leg 1',
    'Notional Currency 1': 'Notional currency-Leg 1',
    'Total Notional Quantity 1': 'Total notional quantity-Leg 1',
    'Price 1': 'Price',
    'Price Unit Of Measure 1': 'Price unit of measure',
    'Underlying Asset ID': 'Underlier ID-Leg 1',
    'Underlying Asset ID Type': 'Underlier ID source-Leg 1'
}




ch_settings = {
    'host': '192.168.8.246',
    'port': 8123,
    'database': 'default',
    'username': 'default',
    'password': ''
}


# sources = [
#     {
#         "name": "finra",
#         "jurisdictions": {[
#             "CFTC": {[
#                 "report_types": ['SLICE', 'CUMULATIVE', 'FOREX', 'INTEREST'],
#                 "asset_classes": ['CREDITS', 'EQUITIES', 'RATES']
#             ]},
#                 "SEC": {[
#                 "report_types": ['SLICE', 'CUMULATIVE'],
#                 "asset_classes": ['CREDITS', 'EQUITIES', 'RATES']
#             ]},  
#         ]},
#         "urlsstr": f"https://pddata.dtcc.com/ppd/api/report/cumulative/{jurisdiction}/{jurisdiction}_{report_type}_{asset_class}_{datestr}.zip"
#         "datefmt": "%Y_%m_%d"
#     }
#     {
#         "name": "ice",
#         "urlstr": f"https://tradevault.ice.com/tvsec/ticker/webpi/exportTicks?date={datestr}",
#         "datefmt": "%Y-%m-%d"
#     },
#     {
#         "name": "cboe",
#         "urlstr": f"https://www.cboe.com/us/equities/market_statistics/reg_sho_threshold/{datestr}/csv",
#         "datefmt": "%Y-%m-%d"
#     },
    # {
    #     "name": "cme",
    #     "asset_classes":['commodities', 'equity', 'credit', 'fx', 'rates'],
    #     "urlstr": f"https://www.cmegroup.com/ftp/sdr/{asset_class}/{year}/{month}/RT.{asset_class.upper()}.{datestr}.csv.zip",
    #     "datefmt": "%Y%m%d",
    #     "yearfmt": "YYYY",
    #     "monthfmt": "mm"
#     }   
# ]
