version: '3.8'

services:
  paradedb:
    image: paradedb/paradedb:latest
    container_name: paradedb
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "${PARADE_DATA_PATH:-./data}:/var/lib/postgresql/data"


