version: '3.8'

services:
  # server:
  #   build: ./server
  #   volumes:
  #     - ./server/config/dashboards:/app/dashboards
  #   ports:
  #     - '3001:3001'
  #   depends_on:
  #     - cloudflare

  client:
    build: 
      context: ./client

    ports:
      - '3006:3000'
    env_file: 
      - ./client/.env
    # depends_on:
    #   - server
      
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: spotlight-cloudlfare
    command: tunnel --config /etc/cloudflared/config.yaml run
    volumes:
      - ./cloudflare:/etc/cloudflared
  
