version: '3.8'

services:
  server:
    build: ./server
    volumes:
      - ./server/config/dashboards:/app/dashboards
    ports:
      - '3001:3001'

  client:
    build: ./client
    ports:
      - '3006:3000'
    depends_on:
      - cloudflare
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: spotlight-cloudlfare
    command: tunnel --config /etc/cloudflared/config.yaml run
    volumes:
      - ./cloudflare:/etc/cloudflared
  
