root_user         = "${env("ROOT_USER")}"
root_password     = "${env("ROOT_PASSWORD")}"
port              = "${env("PORT")}"
console_port      = "${env("CONSOLE_PORT")}"
server_url        = "${env("SERVER_URL")}"
endpoint          = "${env("ENDPOINT")}"
